apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: drupal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: pingwin4ik\drupal:v3
        ports:
        - containerPort: 80
