apiVersion: v1
kind: Service
metadata:
  name: drupal
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: drupal
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drupal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: pingwin4ik/drupal:v3
       # args: ["/bin/sh","-c","cd /var/www/html && drush si -y --db-url=mysql://root:root@my-drupaldb/drupal","chown -R www-data:www-data /var/www/html/sites/default/files","cd /var/www/html && drush en token -y","cd /var/www/html && drush uli -l http://localhost:$DRUPALPORT"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: drupal-persistent-storage
          mountPath: /var/www/html/modules/
      volumes:
      - name: drupal-persistent-storage
        persistentVolumeClaim:
          claimName: dp-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dp-pv-claim
  labels:
    app: drupal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
      requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: my-drupaldb
  labels:
    name: my-drupaldb

spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
  selector:
    app: my-drupaldb

---
apiVersion: v1
kind: ReplicationController
metadata:
  generation: 1
  labels:
    app: my-drupaldb
  name: my-drupaldb
  namespace: jenkins

spec:
  replicas: 1
  selector:
    app: my-drupaldb
  template:
    metadata:
      labels:
        app: my-drupaldb

    spec:
      containers:
      - name: mysql
        image: mariadb
        ports:
        - name: mariadb
          containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USER
          value: superuser
        - name: MYSQL_PASSWORD
          value: passwort
        - name: MYSQL_DATABASE
          value: drupal
